name: Python

on: workflow_dispatch

jobs:
  build3_8:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Display Python version
        run: python -c "import sys; print(sys.version)" > bob3_8.txt
      - name: bob
        uses: actions/upload-artifact@v1
        with:
          name: python3.8
          path: bob3_8.txt


  build3_9:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Display Python version
        run: python -c "import sys; print(sys.version)" > bob3_9.txt
      - name: bob
        uses: actions/upload-artifact@v1
        with:
          name: python3.9
          path: bob3_9.txt
        
  build3_10:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Display Python version
        run: python -c "import sys; print(sys.version)" > bob3_10.txt
      - name: bob
        uses: actions/upload-artifact@v1
        with:
          name: python3.10
          path: bob3_10.txt
